name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: 1.15.8
            otp: 26.2

          - elixir: 1.18.2
            otp: 27.2
            lint: lint

    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps and _build cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install dependencies
      run: mix deps.get --only test

    - name: Remove compiled application files
      run: mix clean

    - name: Compile
      run: mix compile
      if: ${{ !matrix.lint }}

    - name: Compile & lint
      run: mix compile --warnings-as-errors
      if: ${{ matrix.lint }}

    - name: Check if formatted
      run: mix format --check-formatted
      if: ${{ matrix.lint }}

    - name: Check for unused deps
      run: mix deps.unlock --check-unused

    - name: Run tests
      run: mix test --warnings-as-errors
